### ISSUE TITLE
Add card component

### ISSUE THREAD

**Issue by Lancelot2PKR** [jcfatjo/card-game#7]
**Description**
Add the card component, model and some related properties or constants.
The card should have a `type` and a `value`.
The card `type` can be either of the 5 elements: Fire, Water, Earth, Air or Ether.

**Tasks**
- [x] Add card model.
- [x] Add card types enum.
- [ ] Add card component.
- [ ] Add card styles.
- [ ] Add some other properties/constants.

**DoD**
- [x] Card model with its properties is created.
- [x] Card types enum is created.
- [ ] Card component is created.
- [ ] Card styles should automatically change with different card properties.
- [ ] Card component can be added in the main view.
