### ISSUE TITLE
Add board component

### ISSUE THREAD

**Issue by Lancelot2PKR** [jcfatjo/card-game#8]
**Description**
Add the board component, model and some related properties or constants.
The board should have an `initial card`, a list of `future cards` and a list of `revealed cards`.

- The `initial card` is the new generated card.
- The `future cards` is a list of the next cards to be revealed. It's composed by 4 visible cards + 2 hidden cards.
- The `revealed cards` is a list of the cards that were revealed to the user.

**Tasks**
- [ ] Add board component.
- [ ] Add cards to board component.
- [ ] Add board styles.
- [ ] Add some other properties/constants.

**DoD**
- [ ] Board component is created.
- [ ] Board cards should be correctly shown in the board component.
- [ ] Board component can be added in the main view.
